schema = 3

[mod]
  [mod."github.com/aead/chacha20"]
    version = "v0.0.0-20180709150244-8b13a72661da"
    hash = "sha256-2ZTtI0mvOD6oK41tf3C4G+/1JaH4lK109qviNQt+dT0="
  [mod."github.com/aead/chacha20poly1305"]
    version = "v0.0.0-20201124145622-1a5aba2a8b29"
    hash = "sha256-pecdSAZ62Dcu8UGMsDDQVchxL/bsxTde4bLkwYn7hmo="
  [mod."github.com/aead/poly1305"]
    version = "v0.0.0-20180717145839-3fee0db0b635"
    hash = "sha256-qRu/5mowKW9WVzI99XPnT78yQV+UrkY6YO6WPL3/5t8="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.1.1"
    hash = "sha256-cF+sDnnTZ1xRwjsy08SVSV/JoZalwY+dg0Zkghy6BNw="
  [mod."github.com/codenotary/immudb"]
    version = "v1.2.2-0.20211224171643-06d4378fbf62"
    hash = "sha256-2s+DPxndmKHIrmCDYSyZChmdo8IlDPby7tp3A0yXttA="
  [mod."github.com/codenotary/immugorm"]
    version = "v0.0.0-20220117103200-5d136efdb292"
    hash = "sha256-+v4fsexTB4HqnNRavjXZqR+Q1eSUHm5xrtp4ZUs5Ids="
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.4.9"
    hash = "sha256-HZBMhbFqcZM9oxSbWqISzEE7GF7JZpco5tyta6c4OcQ="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.2"
    hash = "sha256-IVwooaIo46iq7euSSVWTBAdKd+2DUaJ67MtBao1DpBI="
  [mod."github.com/grpc-ecosystem/go-grpc-middleware"]
    version = "v1.3.0"
    hash = "sha256-seaTQMNz/lWzpR3ex2gSM1Yo2yD2q6bJQZvB1L3CONk="
  [mod."github.com/grpc-ecosystem/grpc-gateway"]
    version = "v1.16.0"
    hash = "sha256-wLymGic7wZ6fSiBYDAaGqnQ9Ste1fUWeqXeolZXCHvI="
  [mod."github.com/hashicorp/hcl"]
    version = "v1.0.0"
    hash = "sha256-xsRCmYyBfglMxeWUvTZqkaRLSW+V2FvNodEDjTGg1WA="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.0.0"
    hash = "sha256-ogTuLrV40FwS4ueo4hh6hi1wPywOI+LyIqfNjsibwNY="
  [mod."github.com/jinzhu/inflection"]
    version = "v1.0.0"
    hash = "sha256-3h3pHib5MaCXKyKLIMyQnSptDJ16kPjCOQPoEBoQsZg="
  [mod."github.com/jinzhu/now"]
    version = "v1.1.3"
    hash = "sha256-xG/XJqhRhu2W0ggSGx4nAUYIlT+CMDnzvuZxvc5ylsI="
  [mod."github.com/magiconair/properties"]
    version = "v1.8.5"
    hash = "sha256-dnVYJAEVGfVthpfcW3G1tsEZl8APaFgXXQ4MBqd9imw="
  [mod."github.com/matttproud/golang_protobuf_extensions"]
    version = "v1.0.1"
    hash = "sha256-ystDNStxR90j4CK+AMcEQ5oyYFRgWoGdvWlS0XQMDLQ="
  [mod."github.com/mitchellh/mapstructure"]
    version = "v1.4.1"
    hash = "sha256-+xC5Th05FPFaWNMdAuX9YCwZpj0X1SD2t22a1VTkKNU="
  [mod."github.com/o1egl/paseto"]
    version = "v1.0.0"
    hash = "sha256-mw5Pd2KpIzoPbbdxBwu54oqTt/zgXfkcNPjLkSgQQ5U="
  [mod."github.com/pelletier/go-toml"]
    version = "v1.9.3"
    hash = "sha256-2bTSt1K6eDceRIIpNfv3HepMqoCrOIC7Ufnrj2x4yJg="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.11.0"
    hash = "sha256-wwuQogdxDw8/egvZVGJ1smS46XwnB332Avdxw6e/uvU="
  [mod."github.com/prometheus/client_model"]
    version = "v0.2.0"
    hash = "sha256-LTHxYPRgoggl+v89ly2/RkyPIuJlmZRdGs6ZRtK3zkk="
  [mod."github.com/prometheus/common"]
    version = "v0.29.0"
    hash = "sha256-VQB8GcCFYc/nyQJHUu8fVajHbrNd5PlqcVMXAEbd6ic="
  [mod."github.com/prometheus/procfs"]
    version = "v0.7.1"
    hash = "sha256-lBbiIkh5mVGqAEfQGZ1m2k9xKkAczrk+Z4FpNKyaP2s="
  [mod."github.com/rogpeppe/go-internal"]
    version = "v1.8.0"
    hash = "sha256-ze+/FkW3z3b+frAksjWPjDolP1UtSf6z0By6PGXTirM="
  [mod."github.com/rs/xid"]
    version = "v1.3.0"
    hash = "sha256-a1HtvEujd/C4E/IdXpLazqk+R7dm8fyN9SbY6o3aUHA="
  [mod."github.com/spf13/afero"]
    version = "v1.6.0"
    hash = "sha256-ZzzshKZRvdo9JlPlhJ7VVymGfRSvP8XIY7fF2D24KHo="
  [mod."github.com/spf13/cast"]
    version = "v1.3.1"
    hash = "sha256-wT6IRl4ZFvzeyLlv7l/GJt39shnRRYHzxyDTh9AhaFE="
  [mod."github.com/spf13/cobra"]
    version = "v1.2.1"
    hash = "sha256-UCbA7/zPhcpJ+4B6KzVaKDtPsoS2MAfSwvdpavv4MyQ="
  [mod."github.com/spf13/jwalterweatherman"]
    version = "v1.1.0"
    hash = "sha256-62BQtqTLF/eVrTOr7pUXE7AiHRjOVC8jQs3/Ehmflfs="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/spf13/viper"]
    version = "v1.8.1"
    hash = "sha256-BkMQy6r+isc+cRZSDGTftApMyGXxG1UzCPsWQFPbmkk="
  [mod."github.com/subosito/gotenv"]
    version = "v1.2.0"
    hash = "sha256-RUsfBl9xvHk8H6SPwiLi/BpHjkyO/YLvlFmRfGRIW1U="
  [mod."golang.org/x/crypto"]
    version = "v0.0.0-20210711020723-a769d52b0f97"
    hash = "sha256-VsdKY9wMrn59WsT3y9Lrx7rOgfBaJklorSeaMOcpDTk="
  [mod."golang.org/x/net"]
    version = "v0.0.0-20210716203947-853a461950ff"
    hash = "sha256-Vr8T9YQsGq47z29sPSdI5Cd+DyRHxF6JnDsJDntnrW0="
  [mod."golang.org/x/sys"]
    version = "v0.0.0-20210630005230-0f9fa26af87c"
    hash = "sha256-VNz/kjQz9xfCH/Pq4V7u7MqvXtw2wA7STfPLeEERClU="
  [mod."golang.org/x/term"]
    version = "v0.0.0-20201126162022-7de9c90e9dd1"
    hash = "sha256-ykpqi1F7Yzo1BVwuG0nbQOZnK0qevcCD2xqbXbsoQq0="
  [mod."golang.org/x/text"]
    version = "v0.3.6"
    hash = "sha256-yP/VW8PvNE6ub82oSu0mnG3VZXMo1PCSbwsWbciQDaw="
  [mod."google.golang.org/genproto"]
    version = "v0.0.0-20210722135532-667f2b7c528f"
    hash = "sha256-DGF0aHWS9CruaYiJ/4oHImCtRoeVILcBHi+xXFP5AtI="
  [mod."google.golang.org/grpc"]
    version = "v1.40.0"
    hash = "sha256-8O5svL9J3wgPuwQrCl59ZpNlmasR6bP1PO1i3QC+5mw="
  [mod."google.golang.org/protobuf"]
    version = "v1.27.1"
    hash = "sha256-klLGFG4InPHIBDgisRph7H/02D5rBVx0ho9rZCRyLbk="
  [mod."gopkg.in/ini.v1"]
    version = "v1.62.0"
    hash = "sha256-u9T6wgmbmG+hw8qiGLkWdxo9DgdrChFpuVpR53HzqbY="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."gorm.io/gorm"]
    version = "v1.22.4"
    hash = "sha256-2dePNhTRFMhiS+r/7cjQWuneiInfsZOS1HXg28KQApw="
