name: "CI"
on: ["push", "pull_request"]

jobs:
  tests:
    runs-on: ubuntu-22.04
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - name: "Run static analysis and unit tests"
        run: nix flake check
      - name: "Build Docker image"
        run: nix build .#docker
      - name: "Build native binary"
        run: nix build .#bin