name: "CI"
on: ["push", "pull_request"]

jobs:
  tests:
    runs-on: ubuntu-22.04
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: "Build Docker image"
        run: nix build .#docker
      - name: "Build native binary"
        run: nix build .#bin
      - name: "Static check"
        run: >-
          nix develop --command staticcheck ./...
      - name: "Revive"
        run: >-
          nix develop --command revive ./...
      - name: "Go vet"
        run: >-
          nix develop --command go vet ./...
      - name: "Go test"
        run: >-
          nix develop --command go test
          -race
          -coverprofile=coverage.txt
          -covermode atomic
          ./...
      - name: "Upload coverage report"
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.txt